services:
  server:
    image: itzg/minecraft-server
    volumes:
      - ./data:/data
    environment:
      - EULA=TRUE
      - MEMORY=2G
    ports:
      - 25565:25565
    deploy:
      resources:
        limits:
          memory: 2G
